spring:
  application:
    name: learning
  datasource:
    url: jdbc:postgresql://localhost:5432/practice_kafka
    username: kafka
    password: kafka
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-chapter15.sql
  kafka:
    consumer:
      group-id: chapter15-default-group
      auto-offset-reset: earliest